global:
  resolve_timeout: 5m

route:
  receiver: default
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: default
    # Example email configuration
    email_configs:
      - to: your-team@example.com
        from: alertmanager@example.com
        smarthost: smtp.example.com:587
        auth_username: smtp-user
        auth_password: smtp-password
    # Example Slack configuration
    slack_configs:
      - api_url: https://hooks.slack.com/services/EXAMPLE/EXAMPLE/EXAMPLE
        channel: '#alerts'
